name = "solarroots-directory"
main = "src/index.ts"
compatibility_date = "2024-10-07"

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "solarroots-directory"
database_id = "b855288a-242c-4e77-8b49-944dff3d63ba"
migrations_dir = "db/migrations"
