name = "solarroots-directory"
main = "src/index.ts"
compatibility_date = "2024-10-07"

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "solarroots_directory"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
migrations_dir = "db/migrations"
